'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace Bolpa

    Partial Public Class CuentaPorCobrar
        Public Property CodigoFactura As Integer
        Public Property FechaVencimiento As Date
        Public Property EstadoCancelacion As String
    
        Public Overridable Property TbFactura As TbFactura
    
    End Class

End Namespace
