'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace Bolpa

    Partial Public Class TbArticulo
        Public Property CodigoArticulo As Integer
        Public Property Nombre As String
        Public Property CodigoFamilia As Integer
        Public Property CodigoSubFamilia As Integer
        Public Property Imagen As String
        Public Property FechaCaducidad As Date
        Public Property ImpuestoVenta As Integer
    
        Public Overridable Property TbFamilia As TbFamilia
        Public Overridable Property TbSubFamilia As TbSubFamilia
        Public Overridable Property TbFactura As ICollection(Of TbFactura) = New HashSet(Of TbFactura)
        Public Overridable Property TbInventario As ICollection(Of TbInventario) = New HashSet(Of TbInventario)
        Public Overridable Property TbPedidos As ICollection(Of TbPedidos) = New HashSet(Of TbPedidos)
    
    End Class

End Namespace
