'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace Bolpa

    Partial Public Class TbCliente
        Public Property CodigoCliente As Integer
        Public Property Nombre As String
        Public Property Direccion As String
        Public Property Correo As String
        Public Property Telefono As String
        Public Property TipoCliente As String
    
        Public Overridable Property TbFactura As ICollection(Of TbFactura) = New HashSet(Of TbFactura)
        Public Overridable Property TbFisico As ICollection(Of TbFisico) = New HashSet(Of TbFisico)
        Public Overridable Property TbJuridico As ICollection(Of TbJuridico) = New HashSet(Of TbJuridico)
    
    End Class

End Namespace
