'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace Bolpa

    Partial Public Class TbCuentaPorPagar
        Public Property Fecha As Date
        Public Property CodigoFactura As Integer
        Public Property CodigoProveedor As Integer
        Public Property CodigoPedidos As Integer
        Public Property Total As Decimal
    
        Public Overridable Property TbPedidos As TbPedidos
        Public Overridable Property TbProveedor As TbProveedor
    
    End Class

End Namespace
