'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace Bolpa

    Partial Public Class TbEmpleado
        Public Property CodigoEmpleado As Integer
        Public Property Cedula As String
        Public Property Nombre As String
        Public Property Correo As String
        Public Property NomUsuario As String
        Public Property Contraseña As String
        Public Property Telefono As String
        Public Property Horario As String
        Public Property CodigoPuesto As Integer
        Public Property Puesto As String
        Public Property Salario As Decimal
    
        Public Overridable Property TbFactura As ICollection(Of TbFactura) = New HashSet(Of TbFactura)
    
    End Class

End Namespace
