'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace Bolpa

    Partial Public Class TbFamilia
        Public Property CodigoFamilia As Integer
        Public Property Nombre As String
    
        Public Overridable Property TbArticulo As ICollection(Of TbArticulo) = New HashSet(Of TbArticulo)
    
    End Class

End Namespace
