'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace Bolpa

    Partial Public Class TbFactura
        Public Property Fecha As Date
        Public Property CodigoFactura As Integer
        Public Property CodigoEmpleado As Integer
        Public Property CodigoCliente As Integer
        Public Property CodigoArticulo As Integer
        Public Property Tipo As String
        Public Property Descuento As Integer
    
        Public Overridable Property TbArticulo As TbArticulo
        Public Overridable Property TbCliente As TbCliente
        Public Overridable Property TbEmpleado As TbEmpleado
        Public Overridable Property CuentaPorCobrar As ICollection(Of CuentaPorCobrar) = New HashSet(Of CuentaPorCobrar)
    
    End Class

End Namespace
