'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace Bolpa

    Partial Public Class TbFisico
        Public Property Codigo As Integer
        Public Property Apellido1 As String
        Public Property Apellido2 As String
        Public Property FechaNacimiento As Date
        Public Property Genero As String
    
        Public Overridable Property TbCliente As TbCliente
        Public Overridable Property TbProveedor As TbProveedor
    
    End Class

End Namespace
