'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace Bolpa

    Partial Public Class TbInventario
        Public Property CodigoArticulo As Integer
        Public Property Precio As Decimal
        Public Property Cantidad As Integer
    
        Public Overridable Property TbArticulo As TbArticulo
    
    End Class

End Namespace
