'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace Bolpa

    Partial Public Class TbJuridico
        Public Property Codigo As Integer
        Public Property Representante As String
        Public Property Apellido1Repre As String
        Public Property Apelido2Repre As String
        Public Property TelRepresentante As String
        Public Property Canton As String
        Public Property Provincia As String
    
        Public Overridable Property TbCliente As TbCliente
        Public Overridable Property TbProveedor As TbProveedor
    
    End Class

End Namespace
