'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace Bolpa

    Partial Public Class TbPedidos
        Public Property CodigoPedido As Integer
        Public Property CodigoArticulo As Integer
        Public Property CodigoProveedor As Integer
        Public Property Cantidad As Integer
    
        Public Overridable Property TbArticulo As TbArticulo
        Public Overridable Property TbCuentaPorPagar As ICollection(Of TbCuentaPorPagar) = New HashSet(Of TbCuentaPorPagar)
        Public Overridable Property TbProveedor As TbProveedor
    
    End Class

End Namespace
